#!/bin/bash

# 🎯 NeoStream Quick Commands Reference

echo "🎬 NEOSTREAM - QUICK COMMANDS"
echo "=============================="
echo ""
echo "📱 START APP:"
echo "   npx react-native start --reset-cache"
echo "   npx react-native run-android"
echo ""
echo "🔄 RELOAD APP:"
echo "   ~/Library/Android/sdk/platform-tools/adb shell input keyevent 82"
echo ""
echo "📊 VIEW LOGS:"
echo "   npx react-native log-android | grep -E '(channels|Video|Player)'"
echo ""
echo "🚪 LOGOUT & RESET:"
echo "   ./logout.sh"
echo ""
echo "🧪 TEST FEATURES:"
echo "   ./test-channel-display.sh"
echo ""
echo "📺 CURRENT STATUS:"
echo "   ✅ Login works"
echo "   ✅ 11,863 channels loaded"
echo "   ✅ Channels display (paginated)"
echo "   ✅ Search works"
echo "   ⏳ Video playback UNTESTED"
echo ""
echo "🎯 NEXT STEP:"
echo "   → Select any channel in the app"
echo "   → Check if video plays"
echo "   → Report any errors"
echo ""
